# Generated by Django 5.0.7 on 2024-12-06 18:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenentapp', '0002_tenentprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenentprofile',
            options={'verbose_name': 'Tenant Profile', 'verbose_name_plural': 'Tenant Profiles'},
        ),
        migrations.AddField(
            model_name='tenentprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tenentprofile',
            name='email',
            field=models.EmailField(blank=True, help_text='Your email address', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenentprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tenentprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Your complete address', null=True),
        ),
        migrations.AlterField(
            model_name='tenentprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter your contact number', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tenentprofile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Upload a profile picture (Optional)', null=True, upload_to='tenent_profile_images/'),
        ),
    ]
