# Generated by Django 5.1.1 on 2024-10-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0005_ownerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
