# Generated by Django 5.1.1 on 2024-10-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0006_ownerprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='occupancy_status',
            field=models.CharField(default='Available', max_length=20),
        ),
    ]
