# Generated by Django 5.1.1 on 2024-10-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0010_alter_property_owner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='owner_name',
            field=models.CharField(default='Unknown Owner', max_length=100),
        ),
    ]
