# Generated by Django 5.1.1 on 2024-10-13 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0012_property_owner'),
        ('tenentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_file', models.FileField(upload_to='contracts/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Completed', 'Completed')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ownerapp.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenentapp.tenentuser')),
            ],
        ),
    ]
