# Generated by Django 5.0.7 on 2024-11-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0015_rename_issue_description_maintenancerequest_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='overview',
            field=models.TextField(max_length=100),
        ),
    ]
