# Generated by Django 5.0.7 on 2024-11-28 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0019_alter_property_options_remove_property_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='property_address',
            new_name='address',
        ),
        migrations.AddField(
            model_name='property',
            name='occupancy_status',
            field=models.CharField(default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner_name',
            field=models.CharField(default='Unknown Owner', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='size',
            field=models.PositiveIntegerField(),
        ),
    ]
