# Generated by Django 5.0.7 on 2024-11-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0020_rename_property_address_property_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(max_length=255, upload_to='property_images/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image_2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='property_images/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image_3',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='property_images/'),
        ),
    ]
