# Generated by Django 5.1.1 on 2024-11-30 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0022_alter_property_image_alter_property_image_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receiver',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='tenant',
        ),
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
        migrations.AddField(
            model_name='message',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ownerapp.property'),
        ),
        migrations.DeleteModel(
            name='MaintenanceRequest',
        ),
    ]
