# Generated by Django 5.1.1 on 2024-11-30 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0023_rename_receiver_message_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ownerapp.property'),
        ),
    ]
