# Generated by Django 5.0.7 on 2024-12-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0026_alter_message_owner_alter_reply_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
