# Generated by Django 5.0.7 on 2024-12-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0035_alter_property_parking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterField(
            model_name='property',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
