# Generated by Django 5.0.7 on 2024-12-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownerapp', '0036_alter_property_options_alter_property_owner_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={},
        ),
        migrations.AlterField(
            model_name='property',
            name='owner_name',
            field=models.CharField(default='Owner Name', max_length=100),
        ),
    ]
